version: "3.9"

services:
  nb:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/usr/src/workspace
    working_dir: /usr/src/workspace/
    entrypoint: ["jupyter","notebook","--ip='*'","--port=8888", "--no-browser", "--allow-root"]
