---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.3
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

To get maximum benefit from this book, you should know how to program in Python.
(Hint: it's an extremely useful skill to know!)
In particular, knowing how to:

1. use dictionaries,
1. write list comprehensions, and
1. handle `pandas` DataFrames,

will help you a ton during the tutorial.

## Exercises

We have a few exercises below that should help you get warmed up.


### Exercise 1



Given the following line of code:

```python
[s for s in my_fav_things if s[‘name’] == ‘raindrops on roses’]
```

What are plausible data structures for `s` and `my_fav_things`?


`[>]` This could in the simplest terms to be an array of dictionarys where `my_fav_things` is an array and `s` is a dictionary. However, `my_fav_things` does not have to be an array, it could simply be iterable because it have an `__iter__` method. It could be generator function. `s` is a key value pair so I don't think anything but a dictionary would suffice unless you have a data structure that uses this specic notation as an interface.


### Exercise 2


Given the following data:

```{python}
names = [
    {
        'name': 'Eric',
         'surname': 'Ma'
    },
    {
        'name': 'Jeffrey',
        'surname': 'Elmer'
    },
    {
        'name': 'Mike',
        'surname': 'Lee'
    },
    {
        'name': 'Jennifer',
        'surname': 'Elmer'
    }
]
```

Write a function that takes in the `names` list of dictionaries
and returns the dictionaries in which the `surname` value
matches exactly some `query_surname`.

```{python}
def find_persons_with_surname(persons, query_surname):
    # Assert that the persons parameter is a list. 
    # This is a good defensive programming practice.
    assert isinstance(persons, list)   
    
    results = []
    
    # list comprehension
    [results.append(name) for name in persons if name['surname']==query_surname]
    
    # normal if statement
#     for name in persons:
#         if name['surname'] == query_surname:
#             results.append(name)
    
    return results
```

To test your implementation, check it with the following code.
No errors should be raised.

```{python}
# Test your result below.
results = find_persons_with_surname(names, 'Lee')
assert len(results) == 1

results = find_persons_with_surname(names, 'Elmer')
assert len(results) == 2
```
